#include "keyboard.h"


struct KeyNamePair {
  const KeyboardKey key;
  const char* key_name;
};


const struct KeyNamePair g_key_name_map[] = {
  {KEY_BREAK, "KEY_BREAK"},
  {KEY_DOWN, "KEY_DOWN"},
  {KEY_UP, "KEY_UP"},
  {KEY_LEFT, "KEY_LEFT"},
  {KEY_RIGHT, "KEY_RIGHT"},
  {KEY_EIC, "KEY_EIC"},
  {KEY_CLEAR, "KEY_CLEAR"},
  {KEY_HOME, "KEY_HOME"},
  {KEY_BACKSPACE, "KEY_BACKSPACE"},
  {KEY_F(1), "KEY_F1"},
  {KEY_F(2), "KEY_F2"},
  {KEY_F(3), "KEY_F3"},
  {KEY_F(4), "KEY_F4"},
  {KEY_F(5), "KEY_F5"},
  {KEY_F(6), "KEY_F6"},
  {KEY_F(7), "KEY_F7"},
  {KEY_F(8), "KEY_F8"},
  {KEY_F(9), "KEY_F9"},
  {KEY_F(10), "KEY_F10"},
  {KEY_F(11), "KEY_F11"},
  {KEY_F(12), "KEY_F12"},
  {KEY_DL, "KEY_DL"},
  {KEY_IL, "KEY_IL"},
  {KEY_DC, "KEY_DC"},
  {KEY_IC, "KEY_IC"},
  {KEY_EIC, "KEY_EIC"},
  {KEY_CLEAR, "KEY_CLEAR"},
  {KEY_EOS, "KEY_EOS"},
  {KEY_EOL, "KEY_EOL"},
  {KEY_SF, "KEY_SF"},
  {KEY_SR, "KEY_SR"},
  {KEY_NPAGE, "KEY_NPAGE"},
  {KEY_PPAGE, "KEY_PPAGE"},
  {KEY_STAB, "KEY_STAB"},
  {KEY_CTAB, "KEY_CTAB"},
  {KEY_CATAB, "KEY_CATAB"},
  {KEY_ENTER, "KEY_ENTER"},
  {KEY_SRESET, "KEY_SRESET"},
  {KEY_RESET, "KEY_RESET"},
  {KEY_PRINT, "KEY_PRINT"},
  {KEY_LL, "KEY_LL"},
  {KEY_A1, "KEY_A1"},
  {KEY_A3, "KEY_A3"},
  {KEY_B2, "KEY_B2"},
  {KEY_C1, "KEY_C1"},
  {KEY_C3, "KEY_C3"},
  {KEY_BTAB, "KEY_BTAB"},
  {KEY_BEG, "KEY_BEG"},
  {KEY_CANCEL, "KEY_CANCEL"},
  {KEY_CLOSE, "KEY_CLOSE"},
  {KEY_COMMAND, "KEY_COMMAND"},
  {KEY_COPY, "KEY_COPY"},
  {KEY_CREATE, "KEY_CREATE"},
  {KEY_END, "KEY_END"},
  {KEY_EXIT, "KEY_EXIT"},
  {KEY_FIND, "KEY_FIND"},
  {KEY_HELP, "KEY_HELP"},
  {KEY_MARK, "KEY_MARK"},
  {KEY_MESSAGE, "KEY_MESSAGE"},
  {KEY_MOUSE, "KEY_MOUSE"},
  {KEY_MOVE, "KEY_MOVE"},
  {KEY_NEXT, "KEY_NEXT"},
  {KEY_OPEN, "KEY_OPEN"},
  {KEY_OPTIONS, "KEY_OPTIONS"},
  {KEY_PREVIOUS, "KEY_PREVIOUS"},
  {KEY_REDO, "KEY_REDO"},
  {KEY_REFERENCE, "KEY_REFERENCE"},
  {KEY_REFRESH, "KEY_REFRESH"},
  {KEY_REPLACE, "KEY_REPLACE"},
  {KEY_RESIZE, "KEY_RESIZE"},
  {KEY_RESTART, "KEY_RESTART"},
  {KEY_RESUME, "KEY_RESUME"},
  {KEY_SAVE, "KEY_SAVE"},
  {KEY_SBEG, "KEY_SBEG"},
  {KEY_SCANCEL, "KEY_SCANCEL"},
  {KEY_SCOMMAND, "KEY_SCOMMAND"},
  {KEY_SCOPY, "KEY_SCOPY"},
  {KEY_SCREATE, "KEY_SCREATE"},
  {KEY_SDC, "KEY_SDC"},
  {KEY_SDL, "KEY_SDL"},
  {KEY_SELECT, "KEY_SELECT"},
  {KEY_SEND, "KEY_SEND"},
  {KEY_SEOL, "KEY_SEOL"},
  {KEY_SEXIT, "KEY_SEXIT"},
  {KEY_SFIND, "KEY_SFIND"},
  {KEY_SHELP, "KEY_SHELP"},
  {KEY_SHOME, "KEY_SHOME"},
  {KEY_SIC, "KEY_SIC"},
  {KEY_SLEFT, "KEY_SLEFT"},
  {KEY_SMESSAGE, "KEY_SMESSAGE"},
  {KEY_SMOVE, "KEY_SMOVE"},
  {KEY_SNEXT, "KEY_SNEXT"},
  {KEY_SOPTIONS, "KEY_SOPTIONS"},
  {KEY_SPREVIOUS, "KEY_SPREVIOUS"},
  {KEY_SPRINT, "KEY_SPRINT"},
  {KEY_SREDO, "KEY_SREDO"},
  {KEY_SREPLACE, "KEY_SREPLACE"},
  {KEY_SRIGHT, "KEY_SRIGHT"},
  {KEY_SRSUME, "KEY_SRSUME"},
  {KEY_SSAVE, "KEY_SSAVE"},
  {KEY_SSUSPEND, "KEY_SSUSPEND"},
  {KEY_SUNDO, "KEY_SUNDO"},
  {KEY_SUSPEND, "KEY_SUSPEND"},
  {KEY_UNDO, "KEY_UNDO"},
};


const char* keyboard_get_key_name(KeyboardKey key) {
  for (int i = 0; i < array_size(g_key_name_map); i++) {
    if (g_key_name_map[i].key == key) {
      return g_key_name_map[i].key_name;
    }
  }

  log_info_f("Invalid key pressed: {unicode: %d, character: '%c'}", key, (char)key);
  return "";
}